# This is a basic workflow to help you get started with Actions

name: Protect feedback

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  protect:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: GitHub API Request
      uses: actions/github-script@v5
      with:
        script: |
          github.request("PUT /repos/{owner}/{repo}/branches/{branch}/protection", {
            owner: context.repo.owner,
            repo: context.repo.repo,
            branch: "feedback",
            "required_status_checks": {
              "strict": false,
              "contexts": ["Autograding"],
              "checks": [
                {
                  "context": "Autograding",
                  "app_id": 15368
                }
              ]
            },
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": false,
              "require_code_owner_reviews": false,
              "required_approving_review_count": 1
            },
            "restrictions": null
          })

          
